services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    labels:
      glance.name: Outline
      glance.icon: di:outline
      glance.url: https://note.karthihegde.dev
      glance.description: Note and Wiki App
      glance.hide: false
    env_file: stack.env
    ports:
      - "3010:3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    env_file: stack.env
    ports:
      - "6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:16
    env_file: stack.env
    ports:
      - "5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'outuser'
      POSTGRES_PASSWORD: 'outpass'
      POSTGRES_DB: 'outline'

volumes:
  https-portal-data:
  storage-data:
  database-data:
